# Generated by Django 4.1.2 on 2022-12-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('short_disc', models.TextField(max_length=170)),
                ('full_disc', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
